version: '3.8'

services:
  neo4j:
    image: neo4j:5.18
    hostname: neo4j
    container_name: neo4j_db
    ports:
      - "7474:7474" # Browser UI
      - "7687:7687" # Bolt connection
    volumes:
      - ./neo4j-data:/data
    environment:
      - NEO4J_AUTH=neo4j/NAB#Testing25
      - NEO4J_PLUGINS=["apoc"]
    healthcheck:
      test: ["CMD-SHELL", "wget --no-verbose --tries=1 --spider localhost:7474 || exit 1"]
      interval: 5s
      timeout: 10s
      retries: 5
    networks:
      - rag_net

  qdrant:
    image: qdrant/qdrant:latest
    hostname: qdrant
    container_name: qdrant_db
    ports:
      - "6333:6333" # REST API
      - "6334:6334" # gRPC
    volumes:
      - ./qdrant-data:/qdrant/storage
    networks:
      - rag_net

  ollama:
    image: ollama/ollama
    hostname: ollama
    container_name: ollama_service
    ports:
      - "11434:11434"
    volumes:
      - ./ollama_data:/root/.ollama
    networks:
      - rag_net
    deploy:
      resources:
        reservations:
          devices:
            - driver: nvidia
              count: all
              capabilities: [gpu]

  app:
    build:
      context: ./app
    container_name: rag_app
    ports:
      - "8000:8000"
    volumes:
      - ./app:/app
      - ./data_to_import:/app/data_to_import
    depends_on:
      neo4j:
        condition: service_healthy
      qdrant:
        condition: service_started
      ollama:
        condition: service_started
    networks:
      - rag_net
    environment:
      - NEO4J_URI=bolt://neo4j:7687
      - NEO4J_USER=neo4j
      - NEO4J_PASSWORD=NAB#Testing25
      - QDRANT_HOST=qdrant
      - QDRANT_PORT=6333
      - OLLAMA_HOST=http://ollama:11434

networks:
  rag_net:
    driver: bridge